services:
  - type: web
    name: cosmetics-backend
    env: node
    rootDir: ./
    buildCommand: npm install --production
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production